version: '3'
services:
  node:
    depends_on:
      - commerce-mongo
      - users-mongo
    env_file:
      - ./.env
    restart: always
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_INTERNAL_PORT}
    volumes:
      - ./:/code
    links:
      - commerce-mongo
      - users-mongo
    networks:
      - mongo-compose-network
  commerce-mongo:
    image: mongo
    container_name: ecomm
    command: mongod --port ${DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASS}
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./init-mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo-comm.sh:ro
      - mongodb:/data/ecomm-db
    networks:
      - mongo-compose-network
  users-mongo:
    image: mongo
    container_name: ecomm-users
    command: mongod --port ${USERS_DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USERS_DB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${USERS_DB_ADMIN_PASS}
      - MONGODB_USERNAME=${USERS_DB_USER}
      - MONGODB_PASSWORD=${USERS_DB_PASS}
      - MONGO_INITDB_DATABASE=${USERS_DB_NAME}
      - MONGO_PORT=${DB_PORT}
    ports:
      - ${USERS_DB_PORT}:${USERS_DB_PORT}
    volumes:
      - ./init-mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo-users.sh:ro
      - mongodb:/data/users-db
    networks:
      - mongo-compose-network
volumes:
 mongodb:

networks: 
    mongo-compose-network:
      driver: bridge